services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=big_data
      - POSTGRES_HOST_AUTH_METHOD=trust

    volumes:
      - "./big_data_postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  ingest_database:
    build: .
    image: ingest_database
    depends_on:
      - pgdatabase

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
      - "8080:80"
    depends_on:
      - pgdatabase